/**
 * GTrade (Gains Network) Oracle Configuration
 */

export const GAINS_PRICE_HTTP_SERVICE = 'https://backend-pricing.eu.gains.trade/'
export const GAINS_PRICE_WS_SERVICE = 'wss://backend-pricing.eu.gains.trade/v3'

export const GAINS_PAIR_INDEX_MAP: Record<string, number> = {
  "BTC/USD": 0,
  "ETH/USD": 1,
  "LINK/USD": 2,
  "BNB/USD": 3,
  "ADA/USD": 4,
  "MATIC/USD": 5,
  "DOT/USD": 6,
  "UNI/USD": 7,
  "SOL/USD": 8,
  "AVAX/USD": 9,
  "ARB/USD": 10,
  "OP/USD": 11,
  "DOGE/USD": 12,
  "AAVE/USD": 13,
  "EUR/USD": 14,
  "GBP/USD": 15,
  "AUD/USD": 16,
  "USD/JPY": 17,
  "USD/CAD": 18,
  "USD/CHF": 19,
  "NZD/USD": 20,
  "EUR/GBP": 21,
  "EUR/JPY": 22,
  "GBP/JPY": 23,
  "AUD/JPY": 24,
  "EUR/AUD": 25,
  "GBP/AUD": 26,
  "NZD/JPY": 27,
  "EUR/CAD": 28,
  "GBP/CAD": 29,
  "AUD/CAD": 30,
  "EUR/CHF": 31,
  "GBP/CHF": 32,
  "AUD/CHF": 33,
  "CAD/JPY": 34,
  "CHF/JPY": 35,
  "NZD/CAD": 36,
  "NZD/CHF": 37,
  "NOK/USD": 38,
  "SEK/USD": 39,
  "AAPL/USD": 40,
  "ABNB/USD": 41,
  "AMD/USD": 42,
  "AMZN/USD": 43,
  "BA/USD": 44,
  "DIS/USD": 45,
  "GME/USD": 46,
  "GOOGL/USD": 47,
  "INTC/USD": 48,
  "KO/USD": 49,
  "MA/USD": 50,
  "MCD/USD": 51,
  "META/USD": 52,
  "MSFT/USD": 53,
  "NKE/USD": 54,
  "NVDA/USD": 55,
  "PFE/USD": 56,
  "PYPL/USD": 57,
  "SBUX/USD": 58,
  "SNAP/USD": 59,
  "TSLA/USD": 60,
  "V/USD": 61,
  "WMT/USD": 62,
  "COIN/USD": 63,
  "CRCL/USD": 64,
  "HOOD/USD": 65,
  "LMT/USD": 66,
  "RIOT/USD": 67,
  "SBET/USD": 68,
  "PLTR/USD": 69,
  "MARA/USD": 70,
};

