export const MARKET_NAMES: Record<string, string> = {
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  LINK: 'Chainlink',
  BNB: 'Binance Coin',
  ADA: 'Cardano',
  MATIC: 'Polygon',
  DOT: 'Polkadot',
  UNI: 'Uniswap',
  SOL: 'Solana',
  AVAX: 'Avalanche',
  ARB: 'Arbitrum',
  OP: 'Optimism',
  DOGE: 'Dogecoin',
  AAVE: 'Aave',
  EUR: 'Euro',
  GBP: 'British Pound',
  AUD: 'Australian Dollar',
  JPY: 'Japanese Yen',
  CAD: 'Canadian Dollar',
  CHF: 'Swiss Franc',
  NZD: 'New Zealand Dollar',
  NOK: 'Norwegian Krone',
  SEK: 'Swedish Krona',
  AAPL: 'Apple',
  ABNB: 'Airbnb',
  AMD: 'AMD',
  AMZN: 'Amazon',
  BA: 'Boeing',
  DIS: 'Disney',
  GME: 'GameStop',
  GOOGL: 'Google',
  INTC: 'Intel',
  KO: 'Coca-Cola',
  MA: 'Mastercard',
  MCD: "McDonald's",
  META: 'Meta Platforms',
  MSFT: 'Microsoft',
  NKE: 'Nike',
  NVDA: 'Nvidia',
  PFE: 'Pfizer',
  PYPL: 'PayPal',
  SBUX: 'Starbucks',
  SNAP: 'Snapchat',
  TSLA: 'Tesla',
  V: 'Visa',
  WMT: 'Walmart',
  COIN: 'Coinbase',
  CRCL: 'Circle Internet Group',
  HOOD: 'Robinhood Markets',
  LMT: 'Lockheed Martin',
  RIOT: 'Riot Platforms',
  SBET: 'Sharplink Gaming Inc',
  PLTR: 'Palantir Technologies',
  MARA: 'MARA Holdings',
}

export function getMarketName(symbol: string): string {
  const baseSymbol = symbol.split('/')[0]
  return MARKET_NAMES[baseSymbol] || baseSymbol
}

